// Generated by tools/build-i18n.py. Do not edit; edit
// custom_components/hemma/translations/dashboard/*.json and rebuild.
(function () {
  var TABLES = {};

  var cache = { lang: null, table: null };

  function resolve() {
    var root = document.querySelector('home-assistant');
    var lang = (root && root.hass && root.hass.language) || 'en';
    if (cache.lang === lang) return cache.table;
    cache.lang = lang;
    cache.table = TABLES[lang] || TABLES[lang.split('-')[0]] || null;
    return cache.table;
  }

  function fill(s, vars) {
    if (!vars) return s;
    return s.replace(/\{(\w+)\}/g, function (m, k) {
      return Object.prototype.hasOwnProperty.call(vars, k) ? String(vars[k]) : m;
    });
  }

  window._hemmaT = function (key, en, vars) {
    var t = resolve();
    var s = (t && typeof t[key] === 'string' && t[key]) || en;
    return fill(typeof s === 'string' ? s : key, vars);
  };

  window._hemmaI18NLangs = Object.keys(TABLES);

  // Lovelace appends new resources, so this file may load either side of
  // hemma-core.js. Kick whichever waiters core has already flushed.
  if (!resolve()) return;
  var w = window._hemmaCoreWaiters || window._hemmaKicked;
  if (!w || typeof window.hemmaKick !== 'function') return;
  setTimeout(function () {
    w.forEach(function (el) { window.hemmaKick(el); });
  }, 0);
})();
