#!/usr/bin/env python3
"""Compile the dashboard translation tables into a shared frontend script.

Run from the repo root after changing anything under
custom_components/hemma/translations/dashboard/:

    python3 tools/build-i18n.py

en.json is the key reference, not a shipped table: every call site carries its
English default inline so a template painting before this script loads still
reads correctly. Only the other languages are emitted.
"""

import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "custom_components/hemma/translations/dashboard")
OUT = os.path.join(ROOT, "custom_components/hemma/scripts/hemma-i18n.js")

RUNTIME = """// Generated by tools/build-i18n.py. Do not edit; edit
// custom_components/hemma/translations/dashboard/*.json and rebuild.
(function () {
  var TABLES = %s;

  var cache = { lang: null, table: null };

  function resolve() {
    var root = document.querySelector('home-assistant');
    var lang = (root && root.hass && root.hass.language) || 'en';
    if (cache.lang === lang) return cache.table;
    cache.lang = lang;
    cache.table = TABLES[lang] || TABLES[lang.split('-')[0]] || null;
    return cache.table;
  }

  function fill(s, vars) {
    if (!vars) return s;
    return s.replace(/\\{(\\w+)\\}/g, function (m, k) {
      return Object.prototype.hasOwnProperty.call(vars, k) ? String(vars[k]) : m;
    });
  }

  window._hemmaT = function (key, en, vars) {
    var t = resolve();
    var s = (t && typeof t[key] === 'string' && t[key]) || en;
    return fill(typeof s === 'string' ? s : key, vars);
  };

  window._hemmaI18NLangs = Object.keys(TABLES);

  // Lovelace appends new resources, so this file may load either side of
  // hemma-core.js. Kick whichever waiters core has already flushed.
  if (!resolve()) return;
  var w = window._hemmaCoreWaiters || window._hemmaKicked;
  if (!w || typeof window.hemmaKick !== 'function') return;
  setTimeout(function () {
    w.forEach(function (el) { window.hemmaKick(el); });
  }, 0);
})();
"""


def main() -> int:
    if not os.path.isdir(SRC):
        print("no translation source at %s" % SRC, file=sys.stderr)
        return 1

    tables = {}
    for name in sorted(os.listdir(SRC)):
        if not name.endswith(".json") or name == "en.json":
            continue
        lang = name[: -len(".json")]
        with open(os.path.join(SRC, name), encoding="utf-8") as fh:
            data = json.load(fh)
        tables[lang] = {k: v for k, v in sorted(data.items()) if isinstance(v, str)}

    body = json.dumps(tables, ensure_ascii=False, indent=2, sort_keys=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(RUNTIME % body)

    print("wrote %s (%d language(s): %s)" % (
        os.path.relpath(OUT, ROOT), len(tables), ", ".join(tables) or "none"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
